shrinerb/shrine

.travis.yml
test/file_system_test.rb

I run into this issue when running my app using `2.3.0-preview1`. Only the last block of the file would be copied. Not sure why it happens but it seems that `IO.copy_stream(io, filename)`  no longer works as expected. So I changed it to `IO.copy_stream(io, io)`

Ruby 2.3 bug

---

CHANGELOG.md
lib/shrine/plugins/pretty_location.rb
test/plugin/pretty_location_test.rb

Generate a 10 character alpha numeric string for cleaner file URLs.
Did not update the docs because the example in the plugin already shows it generating a 10 character suffix.

Pretty location generates shorter file IDs

---

lib/shrine/storage/s3.rb

- it allows the usage of custom endpoints for presigning files

changed the presign call to use object(id) instead of @bucket

---

index.html

Lotus [has changed its name to Hanami](http://hanamirb.org/blog/2016/01/22/lotus-is-now-hanami.html) and so did my gem and example repository. This PR fixes URLs and names.

Change Lotus into Hanami

---

lib/shrine.rb
test/uploaded_file_test.rb

I'm using Shrine to manage direct S3 uploads and was seeing an unexpected GET to S3 during the `after_commit` phase. This came to light when writing some tests using [webmock](https://github.com/bblimke/webmock) to stub all external network requests.
In the case of an S3 `UploadedFile` that's been initialized from JSON with no processing step required, the copy happily happens on the server and `UploadedFile#io` never needs to be populated. But after the copy completes, the `ensure` block of `UploadedFile#copy` calls `UploadedFile#close`, which references the unpopulated `UploadedFile#io` and triggers `UploadedFile#open`.

Avoid opening an UploadedFile just in order to close it

---

lib/shrine/storage/s3.rb

When S3 credentials are provided then `@s3.client.config.credentials` will be set to an instance of `Aws::Credentials`, which happily responds to `#access_key_id`.
If S3 credentials are not provided explicitly, the aws-sdk gem will search for them in environment variables, ~/.aws/credentials, and by querying the metadata service when running on EC2. In this case, 
`@s3.client.config.credentials` ends up being one of the subclasses of Aws::CredentialProvider. Calling `#access_key_id` on these objects triggers a deprecation warning:
DEPRECATION WARNING: called deprecated method `access_key_id' of an Aws::CredentialProvider, use #credentials instead
Fortunately, both `Aws::Credentials` and `Aws::CredentialProvider` implement `#credentials`, so this change will work in either case.

Fix deprecation warning with implicit S3 credentials

---

lib/shrine/plugins/store_dimensions.rb
test/fixtures/invalid_image.jpg
test/plugin/store_dimensions_test.rb

I made this PR in bit of haste so please review accordingly.
FastImage gem does not rewind IO cursor if the dimension extraction fails eg. due to providing a non-image file. Non rewinded IO causes S3 upload to fail with Aws::S3::Errors::BadDigest before file can be validated.

Rewind IO cursor after failed image dimension extraction by FastImage

---

lib/shrine/plugins/determine_mime_type.rb
test/plugin/determine_mime_type_test.rb

The `file` utility's option parser is greedy and interprets every
argument that begins with a hyphen as an option. This means pathnames
that start with a hyphen cause the command to fail, either by invalid
options or never passing it required input. For example,
`file -image.jpg` looks like combined options and is parsed as `-i`, `-m`,
`-a` (invalid), etc.
To prevent this, `--` is appended to the command to signify the end of
options and allows subsequent arguments to be excluded from option
parsing.
---
Here's [a standalone script](https://gist.github.com/zaeleus/5784e0b966555c5d008ec534ad7b1501) that shows the incorrect behavior.
````
$ wget -O -image.jpg http://i.imgur.com/aDNltvP.jpg
$ wget https://gist.githubusercontent.com/zaeleus/5784e0b966555c5d008ec534ad7b1501/raw/c311f5b098e91eec …
```

Fix file command in determine_mime_type plugin

---

lib/shrine/plugins/direct_upload.rb

Currently, you have to request the presigned POST with something like `...?extension=.jpg`. It would be nice to be able to drop the dot, i.e. `...?extension=jpg`.

Add dot to file extension when missing

---

lib/shrine/plugins/validation_helpers.rb

If we have `jpg` in the whitelist it would make sense to accept `JPG` as well.

Validate extensions case insensitive

---

doc/paperclip.md

This documentation is about migrating from Paperclip to Shrine.
In one sentence, however, documentation misspoke and referenced "CarrierWave" instead of "Paperclip"
This `itty-bitty` commit cleans this up

Updates documentation wording

---

lib/shrine/plugins/metadata_attributes.rb

This PR doesn't really propose any significant changes. At all. 
So I was reading docs on the [MetadataAttribbutes plugin](http://shrinerb.com/rdoc/classes/Shrine/Plugins/MetadataAttributes.html). 
The docs said ```plugin :metadata_values```. 
Decided to try it out... Yup. 
```
LoadError:
cannot load such file -- shrine/plugins/metadata_values
```
Replacing `metadata_values` with `metadata_attributes` did the job.
Checked docs for other plugins (listed at shrinerb.org). Everything else seems okay.

Fix typo in Plugins::MetadataAttributes docs

---

CHANGELOG.md
doc/attacher.md
lib/shrine.rb
test/attachment_test.rb
test/support/helpers.rb

I wrote below snippet to pass `store:` and `cache:` args to Attacher but it did not work.
```rb
include ImageUploader::Attachment.new(:file, store: :private_store, cache: :private_cache)
```
So I implemented it..!

Accept Attacher options via Attachment.new

---

lib/shrine/plugins/determine_mime_type.rb
test/plugin/determine_mime_type_test.rb
test/support/generic_helper.rb

When empty file is passed to determine_mime_type plugin,
- `:file` analyzer will return `"cannot open: No such file or directory"` for mime type string.
- `:filemagic` will raise TypeError, which is caused by passing nil to `filemagic.buffer()`.
This PR fixes it..!
(filemagic one causes SEGV when gcc is used >_< https://github.com/blackwinter/ruby-filemagic/pull/24 )

Fix mime_type on empty file causes TypeError or unexpected value

---

doc/carrierwave.md

A small typo in the Moving from Carrierwave doc
```rb
Shrine.storages = {
cache: Shrine::Storage::S3.new(prefix: "cache", **s3_options),
store: Shrine::Storage::S3.new(prefix: "store", **s3_options),
}
```
instead of 
```rb
Shrine.storages = {
cache: Shrine::Storages::S3.new(prefix: "cache", **s3_options),
store: Shrine::Storages::S3.new(prefix: "store", **s3_options),
}
```

From carrierwave typo in Storage model name

---

shrine.gemspec

As a heavy user of `bundle open` I really appreciate it if the CHANGELOG is part of the gem.

Include CHANGELOG.md in the packaged gem

---

lib/shrine.rb
lib/shrine/storage/file_system.rb
lib/shrine/storage/s3.rb
test/file_system_test.rb
test/s3_test.rb
test/uploaded_file_test.rb

This addresses the issue of ensuring tempfiles are cleared in the event an error occurs during download in base, S3, and FileSystem modules. Implementation is straightforward like we discussed, the challenge was in testing.

Delete tempfile if error occurs during download.

---

lib/shrine.rb
test/uploaded_file_test.rb

Please review this. I think this is what you wanted.
> It would be nice to be able to call Shrine::UploadedFile#open without a block, i.e. to make the block optional.
For the test I copied `#to_io` but I'm not sure why the object_id will be different for the same instance... could you explain what you are testing for here?
```ruby
assert_equal uploaded_file.object_id, uploaded_file.object_id
```

Passing a block to Shrine::UploadedFile#open is now optional.

---

README.md

It's only mentioned in the changelogs and readme, I thought it might be a good idea to promote this information a bit more.
I used monospace for `text`, `json` and `jsonb` since they declare data types, like in the [postgres docs](https://www.postgresql.org/docs/current/static/datatype-json.html).

Add information about json/jsonb column type

---

lib/shrine/storage/s3.rb
test/s3_test.rb

`encode_content_disposition` was using `sub` instead of `gsub`, so only the first `+` was being replaced.
I had a test PDF called "Demo PDF - Google Docs". When I opened the S3 URL in Chrome and pressed CMD+s to save the PDF, the filename was set to: "Demo PDF+-+Google+Docs". This PR fixes the issue, by replacing all of the `+` characters with spaces.

Fix encode_content_disposition - replace all "+" with " ", not just the first one

---

lib/shrine/plugins/logging.rb
test/plugin/logging_test.rb

Fixed a bug in the logging plugin where the logger of Shrine's subclass does not inherit the logging level from Shrine. With this fix, the subclass now correctly inherits the logging level from Shrine and is a copy of the logger so it can be independently configured if needed without affecting the base Shrine logger or other subclass's logger configuration.
I left the default logging level to Logger::INFO which is the current default previously set in the code. This is different from what's stated in issue #246.
Tests added to ensure the behavior reflects the correct inheritance model as described in the issue.
Fixes #246.

Fixed bug in logging plugin so subclasses correctly inherits configuration

---

www/_data/external.yml

This link is dead.
The site is offline, the domain has expired, and the content has not been reposted elsewhere. 🙁

Remove broken article link from homepage

---

lib/shrine/plugins/download_endpoint.rb

Sorting the metadata values by key, so the download_identifier always looks the same regardless of the order of metadata fields. Fixes #261.

Sort metadata for download_identifier

---

lib/shrine/plugins/determine_mime_type.rb
test/plugin/determine_mime_type_test.rb

Fastimage is super fast.
Since I'm already using Fastimage for mime type detection in my uploader class, I figured I could also use it as an analyzer option with the `:determine_mime_type` plugin.
That way, I just have a single dependency for mime type detection. Also, since my app is just uploading image files, I'm trying to optimize my image processing pipeline to be as fast as possible and this helps shave a bit more time off the processing lifecycle.
Tests are passing and it's also working in development for me.

Add Fastimage MIME type analyzer

---

lib/shrine/plugins/validation_helpers.rb
test/plugin/validation_helpers_test.rb

Changes the filesize in the error message to a more human readable version with units upto YB. Filesize is reported in the binary JEDEC unit system where 1.0 KB = 1024 bytes.

Improve the filesize validation error message

---

lib/shrine/plugins/determine_mime_type.rb
test/plugin/determine_mime_type_test.rb

Closes #279.
Not sure how to test for this edge case. Any ideas?

Raise error when mime type plugin opens non-existent file

---

lib/shrine/plugins/versions.rb

This method does NOT, ever, "uses S3's multi delete capabilities."
I think? Am I wrong?
Ah, maybe the _override_ in the deprecated multi-delete plugin WOULD do that -- but the comment doesn't belong here then. It could be here as "overridden by multi_delete to...", but if it's deprecated anyway, maybe no need to mention that.

Remove wrong method comment

---

lib/shrine/plugins/download_endpoint.rb

Hi Janko, thanks for this amazing gem and ecosystem! 
I've just run into a bit of trouble with less helpful looking error messages (though the end of the stacktrace points to the main reason) when adding the download endpoint plugin without having added the `roda` gem to the bundle first. Please decide if you want to add this hint, otherwise you can just close the PR.

Add a code hint for Roda requirement to download endpoint docs

---

lib/shrine/plugins/determine_mime_type.rb
test/plugin/determine_mime_type_test.rb

It appears that the file command can also fail with a successful exit status, in which case the error is returned in stdout. This commit handles that.
So far the only error we know about is
```
cannot open: No such file or directory
```
It's very odd this error happens, because Shrine passes file content to the standard input, it doesn't use a path on disk, so I don't know how this error could happen.
See https://github.com/shrinerb/shrine/issues/303

Fail when file command returned error in stdout

---

doc/metadata.md

When messing with possibilities of refresh_metadata!,I didn't realize it could take a context param. 
Does it make sense to suggest in this example passing in the context, so the possible `add_metadata do |io, context|` invocations will still get a context very much like "normal"?

suggest passing in context to refresh_metadata!

---

CHANGELOG.md
lib/shrine/storage/s3.rb
test/s3_test.rb

Hi, Janko!
First of all, thank you for your a hard work on Shrine! It's a indispensable tool for complex upload workflows with a really sleek design.
Back to PR, I'd like to use a guard raise cause for bucket argument in S3 for an appropriate error message.
Before the change, it fails with a misleading error message mentioning
a missing `name` option (`missing required option :name`).
The raised error originated from S3 gem instead of Shrine.
It leads to a little confusion as a bucket is often configured with
an environment variable which is set by system administrators.

Use a guard raise cause for `bucket` argument in S3

---

lib/shrine.rb
test/attacher_test.rb

to operate on arbitrary UploadedFile, instead of only currently attached (#get) one.
with internal methods changed to use cached? with arg, to allow easier overriding of cached? semantics, to support plugins.
As discussed on google group: https://groups.google.com/d/msg/ruby-shrine/SbeGujDa_k8/dmneazesBAAJ

AttacherMethods#cached? can take an argument

---

CHANGELOG.md
lib/shrine.rb

Hi!
I've changed `class_eval` to `define_method` for `*_attacher` methods, so it has access to attachment (and it's attacher) inside. This removes `ancestors.grep.find` to get attacher class dynamically.

Don't lookup attachment class on every attacher read

---

lib/shrine/uploaded_file.rb
test/shrine_test.rb
test/uploaded_file_test.rb

This seems, to me too, a bit hacky the way it's a special purpose branch, but I couldn't think of a better way.  Didn't see any good way to put this in shrine-url, even though it only matters for shrine-url. 
Test against URI::Regexp to try and avoid messing up anything else (like an actual file with a question mark actually in it's extension?), but do it as last clause cause the earlier short-circuit checks are cheaper. 
Closes shrinerb/shrine-url#4

extract proper extension when id is a shrine-url with query params

---

CHANGELOG.md
doc/creating_storages.md
doc/design.md
lib/shrine/storage/file_system.rb
lib/shrine/storage/linter.rb
lib/shrine/storage/s3.rb
lib/shrine/uploaded_file.rb
test/linter_test.rb
test/s3_test.rb
test/support/test_storage.rb
test/uploaded_file_test.rb

When `refresh_metadata` plugin is used, `UploadedFile#download` using Storage#download causes bad performance when `UploadedFile#download` is called multiple times during metadata extraction, because in that case the same file will be downloaded from the storage multiple times.
```rb
add_metadata :foo do |io, context|
io.download { ... } # downloaded from the storage (1st time)
end
add_metadata :bar do |io, context|
io.download { ... } # downloaded from the storage (2nd time)
end
```
Moreover, the download that `UploadedFile#refresh_metadata!` started at the beginning of metadata extraction won't be reused. It will be reused for determine_mime_type and store_dimensions plugins, but for any custom metadata that uses `UploadedFile#download` (either directly or implicitly via …

Remove Storage#download

---

lib/shrine/storage/s3.rb

Comes from 981ff8c3
Hi, @janko-m 👋 
Was reading the sources and noticed unused variable.

Remove unused variable from S3#initialize

---

CHANGELOG.md
lib/shrine/plugins/derivation_endpoint.rb
test/plugin/derivation_endpoint_test.rb
www/_data/plugins.yml

This pull request brings on-the-fly processing feature to Shrine in the form of a new `derivation_endpoint` plugin, similar to what Active Storage, Refile, and Dragonfly have. This can be used as an alternative to `processing`/`versions` plugins or together.
The reason it's named "*derivation* endpoint" is because we found that "derivation" most closely resembles the result – something that's *derived* from a source file. Btw, the existing `versions` plugin will be getting rewritten soon into a `derivatives` plugin.
First we load the plugin with a secret key and a path prefix to which the endpoint will be mounted:
```rb
class ImageUploader < Shrine
plugin :derivation_endpoint,
secret_key: "<my-secret-key>",
prefix:     "derivations/image"
end
```
And mount a derivation endpoint for our …

Add derivation_endpoint plugin

---

CHANGELOG.md
lib/shrine/plugins/store_dimensions.rb
test/plugin/store_dimensions_test.rb

The store_dimensions method being overridden has an optional second arg. https://github.com/shrinerb/shrine/blob/ee1ced8c99531cbd90df13e75c64953c1e07419a/lib/shrine.rb#L231
By overriding without a default param, the override made the method now have a required second param, basically changing it's signature with the override. Have a matching default arg to preserve semantics on override.
Note I didn't add a test yet, not sure if I should?

extract_metadata in StoreDimensions should have optional second arg

---

lib/shrine/plugins/parsed_json.rb
test/plugin/parsed_json_test.rb

~Removed validation that hash should have at least one string key.
I think attacher already has enough validations, to check provided data~
Check presence of id and storage attributes as
Strings or as Symbols.
Hashes could also be provided by `rack_file` and `versions` plugins.
- Rack file plugin hash values have another keys (`tempfile`, `name`)
- Versions could have same keys, but its quite low possibility somebody has both
`id` and `storage` versions names

Allow assign parsed json with symbol keys

---

lib/shrine/plugins/rack_response.rb
test/plugin/rack_response_test.rb

Range requests that began in a 2nd or later chunk were generating a requested range where the begin value was greater than the end value (eg: `22222..16383`). This caused `chunk.byteslice(...)` to return `nil` instead of a String, which in turn causes Puma (at least--others untested) to raise an exception.
This commit optimizes the begin/end condition to skip the chunk anytime the whole chunk is outside of range, which also avoids the possibility of yielding nil.
It also adds an optimization to end the entire iteration once the Down::ChunkedIO's position has gone past the requested range, which eliminates wasted effort downloading remote data that will be discarded anyway.

Improve multi-chunk range requests

---

doc/plugins/determine_mime_type.md
lib/shrine/plugins/determine_mime_type.rb
test/plugin/determine_mime_type_test.rb

Reverts "Extended determine MIME type with Marcel" commit b1e5d836.
The change was introduced in v2.15.0. Since the filename can be anything, it was found in some small cases the mime-type determined based on filename can be incorrect. This also created a potential security issue for an application because filenames cannot be trusted. Therefore the change is reverted.
This commit allows passing in options to mime-type analyzers in `determine_mime_type` plugin. For now, Marcel is the only analyzer that makes use of any passed-in options but the implementation allows for other analyzers to have options if needed in future.
Marcel analyzer takes one option called `:filename_fallback` which can be set to true or false (default). When set to true, Marcel will also use the filename, if …

Allow options to analyzers in determining_mime_type plugin

---

CHANGELOG.md
lib/shrine/plugins/derivation_endpoint.rb
test/plugin/derivation_endpoint_test.rb

resolve issue https://github.com/shrinerb/shrine/issues/358

Fix derivation_endpoint breaking with moving plugin when :upload is enabled

---

lib/shrine/plugins/derivation_endpoint.rb

Rack::Utils#escape_path has different behaviour for Rack < 2 and Rack >= 2.
Rack < 2 will escape '/' characters in the path while Rack >= 2 does not escape '/'.

Add support to derivation endpoint for Rack < 2

---

lib/shrine/storage/file_system.rb

Fixes #365
Dir.empty? does not load all the child directories into memory. This improves the performance for directories with a lot of children.
I decided to go with implementation that requires Ruby 2.4. We have to drop support for Ruby 2.3 before merging this PR.

Improve check for empty directory in Storage::FileSystem

---

lib/shrine/plugins/versions.rb
test/plugin/versions_test.rb

So both String & Symbol version names are working.
Perhaps this implementation could be "stricter" by simply symbolizing input version without "pre-symbolized" try.
I did it the way it is because I believe this approach is potentially less buggy, all it does is additionally tries symbolized version afterward in case the given one did not work out.

Versions: allow Attacher#url to accept version name indifferently

---

lib/shrine/plugins/processing.rb
test/plugin/processing_test.rb

Cf #379 for the full issue. Long story short, blocks registered via `process` were not behaving as one would expect when defined accross a hierarchy of Uploaders.

Prevent sharing of process blocks between parent and subclasses

---

lib/shrine/plugins/derivation_endpoint.rb

UrlSigner was tightly coupled with internal implementation of Derivation::Url.
Now UrlSigner is a universal class, that accepts single `url` parameter.
This change opens possibility to refactor this code further
- make UrlSigner a separate dependency
- disable signing urls
- providing custom UrlSigner

Refactor derivation endpoint UrlSigner

---

doc/storage/s3.md

Accidentally copy pasted this without noticing the mistake and ran into configuration issues.

Fix typo in S3 documentation

---

doc/plugins/pretty_location.md
lib/shrine.rb
lib/shrine/plugins/pretty_location.rb
test/plugin/pretty_location_test.rb

This PR allows `pretty_location` plugin to use different identifiers when building the location.
[Here](https://groups.google.com/forum/#!topic/ruby-shrine/7Wm1B529I30) is the discussion where this was proposed.

Allow setting the identifier in pretty location plugin

---

lib/shrine/plugins/activerecord.rb

Because the transaction_include_action? method in Rails 3  isn't supporting yet arrays of actions - see the code: https://github.com/rails/rails/blob/3-2-stable/activerecord/lib/active_record/transactions.rb#L370

Fix activerecord plugin's after_commit callbacks to work in Rails 3.

---

CHANGELOG.md
doc/plugins/mirroring.md
lib/shrine/plugins/mirroring.rb
test/plugin/mirroring_test.rb
www/_data/plugins.yml

This adds a new `mirroring` plugin that was requested in https://github.com/shrinerb/shrine/issues/174. This achieves similar functionality as Active Storage's [Mirror Service](https://guides.rubyonrails.org/active_storage_overview.html#mirror-service).
Previously I was recommending [using the `instrumentation` plugin](https://github.com/shrinerb/shrine/wiki/Mirroring-Uploads), but I think the implementation is sufficiently complex (and sufficiently requested) that it makes sense to put it into a plugin.
Tests and docs are still missing, but I just wanted to get preliminary feedback in case anyone wanted to chime in.
You set it up specifying which storage should be mirrored where:
```rb
Shrine.storages = {
cache: Shrine::Storage::S3.new(...),
store: Shrine::Storage::S3.new(...),
gcs: …
```

Add mirroring plugin

---

CHANGELOG.md
doc/plugins/pretty_location.md
lib/shrine/plugins/pretty_location.rb
test/plugin/pretty_location_test.rb

This pull request base on discussion in google group of [pretty print is not pretty](https://groups.google.com/forum/#!searchin/ruby-shrine/pretty%7Csort:date/ruby-shrine/M8KmbVQz6mk/mqz4J9BPAgAJ). 
It is improve the way we transform the class name

improve pretty location class name

---

lib/shrine/storage/linter.rb
test/storage/file_system_test.rb
test/storage/linter_test.rb
test/storage/memory_test.rb

Previously, a test might look like this:
it "passes the linter" do
Shrine::Storage::Linter.call(@memory)
end
If it fails it will raise an exception and fail the test, if it passes nothing happens. So it works. 
But when running MiniTest on that when it succeeds, it reports "0 assertions, 0 errors, 0 failures..."  Which is just kind of weird and not quite right. 
If we make Linter#call reliably return `true` if it finishes, then we can instead write:
it "passes the linter" do
assert Shrine::Storage::Linter.call(@memory)
end
Pretty much exact same thing happens, except MiniTest on success says "1 assertion, 0 errors, 0 failures..." which is somewhat more accurate and more reassuring to see and know that the linter really was run,

Linter#call returns true, so you can make an assertion out of it in a test.

---

doc/creating_storages.md
doc/storage/file_system.md
doc/storage/s3.md
lib/shrine/storage/file_system.rb
lib/shrine/storage/linter.rb
lib/shrine/storage/memory.rb
lib/shrine/storage/s3.rb
test/storage/file_system_test.rb
test/storage/linter_test.rb
test/storage/s3_test.rb

Closes #409
This adds #delete_prefixed to Shrine:Storage::S3 and Shrine::Storage::FileSystem
Also adds docs to creating_storages.md to explain and recommend #delete_prefixed
* Does not add to Memory, although it could add an inefficient imp without too much trouble. 
I could not manage to get a stub_request-style setup to work to test S3, although it oughta be possible. I spent some time with the S3 stub_request docs and experimenting, just couldn't manage to get anywhere yet. Advice or help welcome. 
I DID test it locally -- I wrote a test on a _real_ S3 bucket with my own credentials, and made sure it passed (at first it didn't, finding a bug!). So I am confident in the code at present. But that's not reliable for preventing future regressions of course. 
I DID add testing for …

#delete_prefixed

---

.travis.yml

https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Remove unused `sudo: false` from Travis config

---

doc/storage/file_system.md

Taken from https://github.com/shrinerb/shrine/commit/cea01426d01fb375e74392f78ec3e664514f3966
It took me a couple of minutes to figure this out, since the [release notes for 2.19](https://github.com/shrinerb/shrine/blob/eda05bc3189bc68e7f403bc11250100e4f0d6e34/doc/release_notes/2.19.0.md) just state that the `moving` plugin has been deprecated.
Maybe I should also add this to the release notes? WDYT?

Amend FileSystem documentation wrt moving

---

doc/carrierwave.md

Lint/ShadowingOuterLocalVariable is a rubocop lint error
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/ShadowingOuterLocalVariable

Rename variable to fix Lint/ShadowingOuterLocalVariable

---

website/static/css/custom.css

Add some styling to help separate the ad from the Shrine content without 
being too distracting.
This is what it will look like.

Add a little styling to CodeFund ad

---

doc/paperclip.md

In the paperclip migration guide the link to the Mongoid integration is labelled as Hanami.

Fix Paperclip migration guide typo

---

lib/shrine/storage/memory.rb
test/storage/memory_test.rb

Confirmed the test added here does fail in ruby 2.7.0 without the code change, and passes with the code change.
Also confirmed this code change is what was needed for my actual app, which uses Storage::Memory in tests, to pass it's own tests in ruby 2.7. (Although my actual app is using shrine 2.x still, and made equivalent change in shrine 2.x Storage::Memory).
This appears to be a ruby bug in 2.7.0.
https://bugs.ruby-lang.org/issues/16497
https://www.reddit.com/r/ruby/comments/emd6q4/is_this_a_stringio_bug_in_ruby_270/
Yes, in this test we still need to supply an encoding to the StringIO in the test, also because of the ruby 2.7.0 bug. However, even doing that, the test fails without the code change here, and passes with it. And my actual app needed no other changes than the change here …

Work around apparent StringIO bug in ruby 2.7.0

---

lib/shrine/plugins/upload_endpoint.rb
test/plugin/upload_endpoint_test.rb

Fix IO validation on upload_endpoint as discussed here
https://discourse.shrinerb.com/t/upload-endpoint-with-authorization/121
Helps for example when someone wants to call Shrine.upload_response directly from a rails controller to add authentication.

fix IO validation on upload_endpoint

---

doc/advantages.md

Hi,
This PR fixes a typo in the `advantages.md`, `uplaoded_file` -> `uploaded_file`.

Fix a doc typo

---

CODE_OF_CONDUCT.md

Adds enforcement guidelines amongst other edits.
We recently updated CoC for Bundler due to feedback from few individuals. I thought it will be good to do the same for Shrine.

Update CoC to v2.0

---

doc/processing.md

Don't need to show the old manual way, which there should be no reason to do.

update File Processing guide for new derivatives create_on_promote option

---

CONTRIBUTING.md

- New contributors might not know how to easily run the debugging templates (it took me a not insignificant time to learn how to do it). This PR adds instructions on how this can be done. Hopefully it will be of some use: if not, feel free discard it according to your discretion.
* Hopefully this will lower the barriers to entry to new comers to help debug tests, and that will hopefully ease the maintenance burden for maintainers.

Add: instructions on how to run ruby templates

---

CONTRIBUTING.md
SELF_CONTAINED_EXAMPLE.md

* This PR hopes to make it even easier for developers to get a simple self-contained example of potential problems which may exist. Hopefully this will ease the burden of the maintainers of this Gem in debugging, and help encourage folks to deliver more self-contained examples. Relevant discussion  #475.
* I have added a [simple repository where people can download a self-contained example](https://github.com/BKSpurgeon/debugging-shrine-example) and modify it in less than 5 minutes. Just a simple `git clone` and running the ruby script is all that is needed now - before folks would have to cut and paste templates which might be cumbersome for them. 
* I have created a separate document for instructions re: self-contained example - so people can cut straight to the relevant part.
* …

Add: self contained example templates via a repository

---

doc/plugins/mirroring.md
lib/shrine/plugins/mirroring.rb
test/plugin/mirroring_test.rb

This change allows options to be passed to trigger_mirror_upload, and then to upload. This way you can make e.g. the record en derivative name available to mirror upload. When combining this with the upload options plugin, you can make e.g. the record available there, for using it set S3 acl's.

Enable options to trigger_mirror_upload to make e.g. resource and derivative name available

---

lib/shrine/plugins/backgrounding.rb
test/plugin/upload_endpoint_test.rb
test/shrine_test.rb
test/storage/linter_test.rb

I was seeing some Ruby 2.7 deprecation warnings in my app:
```
/Users/renchap/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/shrine-3.2.1/lib/shrine/plugins/backgrounding.rb:40: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/renchap/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/shrine-3.2.1/lib/shrine/plugins/model.rb:91: warning: The called method `initialize' is defined here
```
Running the tests on my computer with Ruby 2.7.1 was showing some warnings as well (and the Travis build for 2.7 too), so I fixed all of them. I ran `bundle update` to get the latest `activesupport` / `actionrecord` versions fixing other warnings.
Related to #437

Fixes Ruby 2.7 arguments warnings

---

doc/plugins/store_dimensions.md
lib/shrine/plugins/store_dimensions.rb
test/plugin/store_dimensions_test.rb

As discussed here https://discourse.shrinerb.com/t/store-dimensions-with-videos/177
I tried to not define `extract_metadata` if the option is not set, but I have not been able to find out if I can access the options from the module.

Add auto_extraction option to store_dimensions plugin

---

doc/plugins/add_metadata.md
lib/shrine/plugins/add_metadata.rb
test/plugin/add_metadata_test.rb

As discussed here: https://discourse.shrinerb.com/t/restrict-metadata-on-derivatives/175/6
I preferred to store definition options as a hash, so it can be expanded with other options later if needed. Please tell me if this suits you!

Add `skip_nil` option to `add_metadata` plugin

---

doc/plugins/derivatives.md
lib/shrine/plugins/derivatives.rb
test/plugin/derivatives_test.rb

By default ALL `sources` are converted to a local Tempfile before passing to derivative processor. This is done with `with_file` for consistency with other parts of shrine and DRY that logic. 
But option, when registering processor, `raw_source: true` is now available, which will just pass on the source-unaltered -- IO or UploadedFile, for the processor to choose to handle on it's own, in cases where the expense of downloading to localfile is not necessary (conditional logic, or something that can be processed without a local copy, etc). 
Would close #472, based on discussion there. 
Note that all existing shrine tests passed with this change; only new tests were added. I think this further supports my inclination to say that this is backwards compat, any behavior that was changed was …

Derivative processing normalization

---

doc/processing.md

* Fixes a typo (name of the plugin is derivation_endpoint, not derivation_endpoints)

derivation_endpoint typo fix

---

lib/shrine.rb

Fixes https://github.com/shrinerb/shrine/issues/517

Fix for "warning: Using the last argument as keyword parameters is deprecated"

---

doc/direct_s3.md

It seems like they do not support XML format anymore in their new GUI

direct_s3.md: add JSON Bucket CORS config

---

doc/processing.md

* adds secret_key argument for derivation_endpoint plugin to docs
* renames and adds a note re: environment variable for clarity (i.e. you’re not using your Rails secret key)

Updates derivation_endpoint documentation

---

doc/changing_derivatives.md

The module seems to be incorrect and should be ImageProcessing instead.

Fixes incorrect class reference in the “Adding new derivatives” docs.

---

README.md

In the main README.md file on GitHub, you don't provide information about `jsonb` column type that can be used to store assets data.

Added info about `jsonb` column type to README.md

---

README.md
doc/getting_started.md

*  I forgot to add a gin index. Hopefully this will help people remember.
Please feel free to close if this is not useful/beneficial.
Ben

Add: note re: gin index for jsonb

---

lib/shrine/plugins/determine_mime_type.rb
test/plugin/determine_mime_type_test.rb

https://github.com/shrinerb/shrine/issues/539
The determine_mime_type plugin returns the incorrect mime type
for svgs when using the fastimage analyzer. This is because fastimage
is returning a symbol `:svg` as the type, and Shrine is doing a
string interpolation to return `image/` plus whatever fastimage returns.
The correct mime type for svgs is `image/svg+xml`, which requires a
special case in this method since simple string interpolation won't
handle it. So I've added a return value for `image/svg+xml` for this
case.
The SVG in my test is just a straight line that I made in a vector editor.

[#539] Fixes error in mime type given to svgs by fastimage

---

lib/shrine/plugins/infer_extension.rb
test/plugin/infer_extension_test.rb

Same as `calculate_signature`. For a discussion (well, monologue) see [this discourse](https://discourse.shrinerb.com/t/how-to-call-infer-extension-in-custom-plugin-when-defined-as-a-dependency/502/2?u=aried3r).
Just a proposal, doesn't add anything but convenience and maybe more concise code. So if you don't think it should be exposed like this, feel free to just close this. :)

Add `infer_extension` convenience method to uploader

---

doc/upgrading_to_3.md

Fix the typo `beeen` in the upgrade guide.

Fix a typo in upgrading_to_3.md

---

doc/changing_location.md

I added `current_file` just like https://github.com/shrinerb/shrine/commit/12b3e25b81000451e8429fceb7337501da60610b.

Correct usage of #atomic_persist when backgrounding

---

lib/shrine/storage/s3.rb
test/storage/s3_test.rb

It was always using metadata_directive: REPLACE; this does not apply to AWS tags applied to an S3 object. It should also use tagging_directive to apply to AWS tags as well.
This makes it so tags aren't copied when copying from (say) cache to storage. More significantly, it allows the caller to pass S3 `tagging` param in `upload_options`, and have this take effect, whether on a promotion or any other kind of `upload`, regardless of whether the S3 adapter decides to use a `copy_from` operation under the hood.
Without this change, whether `tagging` passed as `upload_options` actually works (as well as whether the destination winds up with copied tags from source) depends on whether the S3 adapter decides to use `copy_from`, which should be an implementation detail that does not effect …

S3 should use tagging_directive REPLACE on copy operation

---

lib/shrine/storage/s3.rb
test/storage/s3_test.rb

Some s3 compatible cloud providers limit the number of multipart part during upload (example scaleway : https://www.scaleway.com/en/docs/storage/object/api-cli/multipart-uploads/).
This PR adds an options on the S3 driver to override the default max multipart part set to 10_000.

Customize max multipart part

---

doc/external/extensions.md

shrine-lambda plugin has been renamed to shrine-aws-lambda

---

doc/plugins/derivatives.md

The URL will be /fallbacks/ not /fallbacks.com/ (probably a bad find/replace/copy/paste of example.com

Correct small typo in doc/plugins/derivatives.md

---

lib/shrine/storage/s3.rb
test/storage/s3_test.rb

When using local file storage with Shrine, a call to `#read` will accept `encoding: ...` in the same way as one might expect for a regular IO object. This is quite important when dealing with input data for things like CSV which might come from all manner of sources, including correctly-encoded UTF-8 with or without BOM, ISO8859-1 or (quite often) Windows CP1252.
In our application, we used this to figure out the encoding and decode the CSV accordingly, but while it works for local development where file storage is convenient for most engineers, it didn't work in deployment since the S3 storage class didn't understand that option and just passed it through to the AWS SDK, which understandably complained.
This PR fixes that in a backwards-compatible way by accepting a with-nil-default …

Allow encoding to be specified with S3 storage class

---

lib/shrine/uploaded_file.rb

`URI.regexp` is obsolete now.
```
$ ruby -w -e 'require "net/http"; URI.regexp'
-e:1: warning: URI.regexp is obsolete
```
This changed to use `URI::DEFAULT_PARSER.make_regexp` that use inside `URI.regexp`
instead of `URI.regexp`.
https://github.com/ruby/uri/blob/6bc8f666219e519c1001673c15adab5182ff05ef/lib/uri/common.rb#L294-L297

Fix "warning: URI.regexp is obsolete"

---

doc/external/articles.md

It seems like the old domain isn't used anymore or the articles were moved away from Github.

Update domain in URLs of official Shrine articles

---

website/docusaurus.config.js

* Close: #646.
* Search bar was not working.
I just changed a config setting, as described here: https://discourse.algolia.com/t/algolia-searchbar-is-not-working-with-docusaurus-v2/14659
all of a sudden the search bar is working:  ![development_server_is_working](https://github.com/shrinerb/shrine/assets/15097447/6e5b3e8c-fccf-4d40-8700-29706f8e698d)
(I am guessing you will need to rebuild / re-index the site etc. I know very little about Docusaurus, pls take all of this with a grain of salt.)

fix: search bar on Docusaurus site

---

lib/shrine/attacher.rb
test/attacher_test.rb
test/plugin/model_test.rb

We hit an issue following the upgrade to 3.5.0 where `context[:record]` in an `Attacher#finalize` call was set to an unpersisted duplicate of the record we were saving. This turned out to be because another part of our model save flow was duplicating the model for its own purposes and the `context` hash was shared between the original attacher and its duplicate.
The changes in fc6a3ed70aab9bff51ec1f0d269ad9553f4b8145  added a call to `attacher_copy.set_entity(self, name) if attacher_copy`. Because `@context` in both attachers point at the same object, this ends up with `context[:record]` for both records pointing to the new duplicate model.

Duplicate the context hash when duplicating an Attacher

---

lib/shrine/uploaded_file.rb
test/plugin/rack_response_test.rb
test/uploaded_file_test.rb

This means removing the reference to the now-closed (and unusable) IO object. Which meant refactoring an existing test slightly, as it tried to refer to the IO object after UploadedFile#close.
Normally you can call UploadedFile#download without having previously opened, it takes care of it. 
```ruby
tmpfile = uploaded_file.download
```
*AND* normally you can open and close an UploadedFile multiple times, no problem. 
```ruby
uploaded_file.open
uploaded_file.close
uploaded_file.open
uploaded_file.close
```
BUT if you have first opened and closed an UploadedFile THEN try to call #download, it complains -- and it's because the UploadedFile actually still thinks it's #opened?
```ruby
uploaded_file.open
uploaded_file.close
uploaded_file.opened? # => true !!!?! this seems wrong …
```

UploadedFile#close should leave uploaded_file in a state where #opened? is false

---

.gitignore
lib/shrine/storage/s3.rb

Currently S3-compatible Cloudflare R2 does not support tagging_directive (https://developers.cloudflare.com/r2/api/s3/api/). This means, we cannot use shrine with tagging_directive. Thus, this Pull Request aims to expose copy_options.
By default, copy_options will have existing value: `{ tagging_directive: "REPLACE" }`
For users like me, we can instantiate S3 store like below until Cloudflare is fully compatible (or just pass additional copy options):
`Shrine::Storage::S3.new(bucket: BUCKET, copy_options: {}, **s3_options),`
This will also solve: https://github.com/shrinerb/shrine/issues/662

Expose copy_options

---

lib/shrine/plugins/backgrounding.rb
test/plugin/backgrounding_test.rb

If `Shrine::Attacher.promote_block { |**options| ... }` is declared with backgrounding plugin and we call `attacher.promote_cached(**options)`, the options were not being forwarded to the `.promote_block`.

forward options when calling #promote_cached to promote_block

---

lib/shrine/plugins/remote_url.rb

```bash
/Users/sbastien/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/shrine-3.6.0/lib/shrine/plugins/remote_url.rb:113: warning: `*' interpreted as argument prefix
```
This PR addresses a warning that appears in Ruby 3+ when using the splat operator (`*`) in the `remote_url_error_message` method. The warning occurs because Ruby 3+ has become more strict about the usage of the splat operator to avoid ambiguity between multiplication and argument splatting.
- Updated the splat operator usage in `remote_url_error_message` to use explicit parentheses
- The functionality remains unchanged
- The warning is no longer present in Ruby 3+
- All existing tests should continue to pass

Add parentheses to method call to fix warning

---

doc/plugins/signature.md

Adds the missing `algorithm` and `format` payload keys to the table and examples, also corrects the default log subscriber name.

Document payload types for signature instrumentation
