doc/direct_s3.md
current http://shrinerb.com/rdoc/files/doc/direct_s3_md.html
=> Add missing link of FineUploader in docs

lib/shrine/storage/s3.rb
Referring to https://github.com/janko-m/shrine/pull/91
=> Don't overwrite option if already set

lib/shrine.rb, lib/shrine/plugins/activerecord.rb, lib/shrine/plugins/sequel.rb
This allows to change serialization logic by overiding Attacher#serialize_data method.
=> Extract serialization logic

lib/shrine/plugins/validation_helpers.rb
=> Small text fix on validation_helpers.rb

CHANGELOG.md, README.md, lib/shrine.rb, test/attacher_test.rb, test/support/generic_helper.rb
Following https://groups.google.com/forum/#!topic/ruby-shrine/sN6Zdg1YJxI
=> Validations inheritance

LICENSE.txt
It seems that the end of period of copyright is 2017.
So I fixed it :)
=> Fix copyright 2015-2016 => 2015-2017

test/file_system_test.rb
Noticed this in the test... don't think it affects anything.
=> Remove unused variable.

lib/shrine/plugins/upload_endpoint.rb
Not sure if you accept cosmetic PRs like this. But here it is :D
=> Fix typos in upload_endpoint.rb

doc/paperclip.md
=> Fix typo in paperclip doc.

lib/shrine/plugins/processing.rb, lib/shrine/plugins/versions.rb
Thought of highlighting how to re-run processing and versions in docs since we get questions on it. Hope this helps.
=> Update docs to better highlight how to re-run processing and versions

doc/carrierwave.md
=> Fix typo with endpoint parameter in carrierwave docs

demo/README.md, demo/app.rb, demo/config/shrine.rb, demo/db/migrations/001_create_albums.rb, demo/db/migrations/002_create_photos.rb, demo/jobs/delete_job.rb, demo/jobs/promote_job.rb, demo/models/album.rb, demo/models/photo.rb, demo/routes/albums.rb, demo/routes/base.rb, demo/routes/direct_upload.rb, demo/uploaders/image_uploader.rb
This is what I had in mind - little notes to guide users along. Let me know what you think.
=> Add comments to Roda demo code and link to Rails demo

doc/multiple_files.md
=> Improve multiple file uploads doc

lib/shrine/storage/s3.rb
Require dependencies prior to initialising.
=> Updated S3 storage documentation

CHANGELOG.md, lib/shrine/plugins/add_metadata.rb, test/plugin/add_metadata_test.rb, test/plugin/refresh_metadata_test.rb, test/plugin/restore_cached_data_test.rb
First pass. Some existing tests fail (for obvious reasons), waiting for feedback on this approach, and any feedback on the "right" way to fix failing tests, before proceeding. Thanks!
=> add_metadata blocks get metadata in context

CHANGELOG.md, lib/shrine.rb, lib/shrine/attacher.rb, lib/shrine/attachment.rb, lib/shrine/plugins.rb, lib/shrine/uploaded_file.rb, test/shrine_test.rb, www/_data/core.yml, www/index.html
=> Inline Base plugin into core classes, extract them to separate files

lib/shrine/attachment.rb, lib/shrine/plugins/activerecord.rb, lib/shrine/plugins/cached_attachment_data.rb, lib/shrine/plugins/copy.rb, lib/shrine/plugins/data_uri.rb, lib/shrine/plugins/migration_helpers.rb, lib/shrine/plugins/module_include.rb, lib/shrine/plugins/remote_url.rb, lib/shrine/plugins/remove_attachment.rb, lib/shrine/plugins/sequel.rb
=> Use define_method instead of evaling strings

README.md
While setting up shrine for the first time, it took longer than expected to figure out how to set it up to "just upload a file". I believe this makes it easier.
_Thanks for creating this gem!_
=> Add instructions for vanilla setup

doc/testing.md
=> Improve testing.md

doc/carrierwave.md, doc/paperclip.md
Hi
currently, I'm migrating from carrierwave to shrine, and met an issue with not respected prefix during dual write. So I've decided to make some workaround to help.
=> Update carrierwave migration doc

doc/plugins/atomic_helpers.md, doc/plugins/persistence.md
I had trouble tracking down the docs to understand what was going on and what tools were available, related to this. 
So I tried writing the docs that would have helped me, including linking the persistence and the atomic_helpers doc pages. 
Just an attempt to be helpful, feel free to let me know if you think this isn't quite right or isn't a useful addition, no worries.
=> Additional documentation on atomic persistence

doc/upgrading_to_3.md
=> Fix syntax in doc

doc/testing.md
Extracted from https://discourse.shrinerb.com/t/how-to-test-direct-upload/411
=> Add `Testing direct upload` documentation

doc/upgrading_to_3.md
=> Fixes an argument in docs.

doc/metadata.md
Small fix mistake in text:
meatadata --> metadata
=> Fix mistake in text

doc/plugins/backgrounding.md
Fixes a sidekiq related deprecation warning.
Fixes #574
=> Cast name to string when asynchronously calling PromoteJob

doc/retrieving_uploads.md
=> Remove duplicate word from retrieving_uploads#opening

doc/changing_location.md
The way that it was worded felt a bit awkward.
=> Update phrasing in `changing_location.md`

doc/processing.md
=> Fix markdown link in processing docs
